### ISSUE TITLE
The png file I exported cannot find the action code in Flash CS6

### ISSUE THREAD

**Issue by xdd-a** [barrydevp/ddt3.8_flash#1]

**Comment by xdd-a** [comment]
The png file I exported cannot find the action code in Flash CS6

**Comment by barrydevp** [comment]
which file did you export? if it is 2.png, 1.png then it cannot open with flash cs6 because they are built by Flash Builder into .swc format.
All source code in the ./src directory is built by Flash Builder to SourceFlash.swc in ./flash/build directory, and then SourceFlash.swc is unzipped to SourceFlash directory that contains library.swf, then library.swf is renamed to 2.png.

**Comment by xdd-a** [comment]
Yes, it only contains script code in 2. png. Can you tell me how I can export and compile it? I want to add a new folder for it, which cannot be done in decompilation

**Comment by barrydevp** [comment]
If you use my 2.png, its script code is all in ./src directory. Open this repository by Flash Builder 4.6 modify any code you want and then click the build button on Flash Builder 4.6, the output will be SourceFlash.swc in ./flash/build directory. Unzip SourceFlash.swc to get library.swf file, renamed to 2.png and put into your server directory.

In other case, you want to export or decompile 2.png from another source, then I'm not capable of that, because each 2.png may use different encryption technique which you must decrypted first then you can decompile it. In my repository, the 2.png file is not encrypted so you can decompile it directly.

**Comment by xdd-a** [comment]
The png I am using here is version 10.8 png, so your png may be a bit low for me, but I still want to thank you for your patient answer and help.

My 2. png can be decompiled into source code using jpex software, but I am unable to recompile the source code into png files, which makes me very distressed

**Comment by barrydevp** [comment]
Actually the decompiled source code by jpex is not really buildable, its kind of messy and you have to fix a bunch of error to get a buildable source which can be seen by opening the whole decompiled source by Flash Builder software. Anw good luck with your journey.

**Comment by xdd-a** [comment]
Thank you
